# Generated by Django 4.1 on 2022-09-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectur', '0005_course_rlt'),
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.IntegerField()),
                ('fild', models.CharField(max_length=255, null=True)),
                ('exp', models.CharField(max_length=255, null=True)),
                ('age', models.DateField(null=True)),
                ('dat', models.DateTimeField(auto_now_add=True, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('rol', models.CharField(max_length=255, null=True)),
                ('type', models.IntegerField(null=True)),
                ('fr', models.CharField(max_length=255, null=True)),
                ('pro', models.CharField(max_length=255, null=True)),
                ('adress', models.CharField(max_length=255, null=True)),
                ('fname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.collage')),
                ('depa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lectur.departiment')),
            ],
        ),
    ]
