# Generated by Django 4.1 on 2022-09-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectur', '0005_course_rlt'),
        ('registeral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='collage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lectur.collage'),
        ),
        migrations.AddField(
            model_name='reg',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
