# Generated by Django 4.1 on 2022-09-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeral', '0002_reg_collage_reg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='token',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
