# Generated by Django 4.1 on 2022-09-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeral', '0003_reg_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.IntegerField(null=True)),
            ],
        ),
    ]
