# Generated by Django 4.1 on 2022-09-16 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_lectur_gender_lectur_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complent',
            name='comfrom',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='block',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='room',
        ),
        migrations.AddField(
            model_name='complent',
            name='adby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.departiment'),
        ),
        migrations.AddField(
            model_name='complent',
            name='dat',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='complent',
            name='dt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lectur',
            name='rol',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='rol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lectur',
            name='dat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reg',
            name='age',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='depart',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descr', models.TextField()),
                ('event', models.CharField(max_length=255)),
                ('eventd', models.TextField()),
                ('dat', models.DateField(null=True)),
                ('dt', models.DateField(auto_now_add=True, null=True)),
                ('adby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
