# Generated by Django 4.1 on 2022-09-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_complent_comfrom_remove_reg_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complent',
            name='adby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.departiment'),
        ),
    ]
