# Generated by Django 4.1 on 2022-09-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_complent_adby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.IntegerField(null=True)),
                ('mark2', models.IntegerField(null=True)),
                ('mark3', models.IntegerField(null=True)),
                ('mark4', models.IntegerField(null=True)),
                ('mark5', models.IntegerField(null=True)),
                ('mark6', models.IntegerField(null=True)),
                ('mark7', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('grade', models.CharField(max_length=255, null=True)),
                ('th', models.IntegerField(null=True)),
                ('adby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.lectur')),
                ('cours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.course')),
                ('depa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.departiment')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Comulative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comu', models.IntegerField(null=True)),
                ('ect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.course')),
                ('th', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.mark')),
            ],
        ),
    ]
