# Generated by Django 4.1 on 2022-09-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectur', '0001_initial'),
        ('main', '0023_mark_comulative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calender',
            name='adby',
        ),
        migrations.RemoveField(
            model_name='course',
            name='adby',
        ),
        migrations.RemoveField(
            model_name='course',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='departiment',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Reg',
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='complent',
            name='adby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.departiment'),
        ),
        migrations.AlterField(
            model_name='comulative',
            name='ect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.course'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='adby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.lectur'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.course'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='depa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.departiment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='depa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.departiment'),
        ),
        migrations.DeleteModel(
            name='Calender',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Departiment',
        ),
        migrations.DeleteModel(
            name='Lectur',
        ),
    ]
