# Generated by Django 4.1 on 2022-09-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectur', '0005_course_rlt'),
        ('main', '0024_remove_calender_adby_remove_course_adby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comulative',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.course'),
        ),
        migrations.AddField(
            model_name='comulative',
            name='did',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.departiment'),
        ),
        migrations.AddField(
            model_name='comulative',
            name='sem',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comulative',
            name='ect',
            field=models.IntegerField(null=True),
        ),
    ]
