# Generated by Django 4.1 on 2022-09-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_comulative_cid_comulative_did_comulative_sem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='token',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
