# Generated by Django 4.1 on 2022-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_student_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
