# Generated by Django 4.1 on 2022-09-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_mark_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complent',
            name='cmd',
            field=models.IntegerField(null=True),
        ),
    ]
