# Generated by Django 4.1 on 2022-09-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_complent_cmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cafe',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='comp',
            field=models.IntegerField(default=0),
        ),
    ]
