# Generated by Django 4.1 on 2022-09-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_student_cafe_student_comp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complent',
            old_name='cmd',
            new_name='stid',
        ),
        migrations.AddField(
            model_name='complent',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complent',
            name='sector',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
