# Generated by Django 4.1 on 2022-09-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_cmd_complent_stid_complent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complent',
            name='stid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
