# Generated by Django 4.1 on 2022-09-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_complent_stid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='fname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='lname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='sid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
