# Generated by Django 4.1 on 2022-09-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur', '0010_feedback'),
        ('main', '0033_mark_sem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['sid']},
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='lectur.course'),
        ),
    ]
