# Generated by Django 4.1 on 2022-09-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_student_options_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='regs',
            field=models.IntegerField(null=True),
        ),
    ]
