# Generated by Django 4.1 on 2022-09-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_student_regs'),
    ]

    operations = [
        migrations.AddField(
            model_name='comulative',
            name='gpa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comulative',
            name='stud',
            field=models.IntegerField(null=True),
        ),
    ]
