# Generated by Django 4.1 on 2022-09-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_comulative_gpa_comulative_stud'),
    ]

    operations = [
        migrations.AddField(
            model_name='comulative',
            name='ectt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comulative',
            name='gpat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comulative',
            name='grade',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
