# Generated by Django 4.1 on 2022-10-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_comulative_ectt_comulative_gpat_comulative_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
