# Generated by Django 4.1 on 2022-11-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_student_cimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cimage',
            field=models.ImageField(null=True, upload_to='Cpicture/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='picture/'),
        ),
    ]
