# Generated by Django 4.1 on 2022-09-20 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('dean', models.CharField(max_length=255, null=True)),
                ('ndepa', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lectur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.IntegerField()),
                ('depa', models.CharField(max_length=255, null=True)),
                ('fild', models.CharField(max_length=255, null=True)),
                ('exp', models.CharField(max_length=255, null=True)),
                ('age', models.DateField(null=True)),
                ('dat', models.DateTimeField(auto_now_add=True, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('rol', models.CharField(max_length=255, null=True)),
                ('type', models.IntegerField(null=True)),
                ('fr', models.CharField(max_length=255, null=True)),
                ('pro', models.CharField(max_length=255, null=True)),
                ('adress', models.CharField(max_length=255, null=True)),
                ('fname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.collage')),
            ],
        ),
        migrations.CreateModel(
            name='Departiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('members', models.IntegerField(null=True)),
                ('descr', models.CharField(max_length=255, null=True)),
                ('yearend', models.IntegerField(null=True)),
                ('nstudent', models.IntegerField(null=True)),
                ('nlectur', models.IntegerField(null=True)),
                ('admin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.collage')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('ccode', models.CharField(max_length=255, unique=True)),
                ('crdt', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('year', models.IntegerField(null=True)),
                ('sem', models.IntegerField(null=True)),
                ('adby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('depart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lectur.departiment')),
            ],
        ),
    ]
