# Generated by Django 4.1 on 2022-09-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur', '0002_alter_lectur_depa'),
    ]

    operations = [
        migrations.AddField(
            model_name='departiment',
            name='adby',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
