# Generated by Django 4.1 on 2022-09-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectur', '0003_departiment_adby'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lectur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lectur.lectur'),
        ),
    ]
