# Generated by Django 4.1 on 2022-09-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur', '0007_lectur_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectur',
            name='token',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
