# Generated by Django 4.1 on 2022-09-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur', '0008_lectur_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='departiment',
            name='hed',
            field=models.IntegerField(null=True),
        ),
    ]
