# Generated by Django 4.1 on 2022-09-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectur', '0009_departiment_hed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciverl', models.IntegerField(null=True)),
                ('senders', models.IntegerField(null=True)),
                ('reciverd', models.IntegerField(null=True)),
                ('senderl', models.IntegerField(null=True)),
                ('recivers', models.IntegerField(null=True)),
                ('senderlb', models.IntegerField(null=True)),
                ('reciverlb', models.IntegerField(null=True)),
                ('senderld', models.IntegerField(null=True)),
                ('msg', models.TextField(null=True)),
                ('rpy', models.TextField(null=True)),
                ('ap', models.CharField(max_length=200, null=True)),
                ('sendap', models.CharField(max_length=100, null=True)),
                ('dt', models.DateField(auto_now=True)),
            ],
        ),
    ]
